services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=settings
      - DATABASE_URL=postgresql://neondb_owner:npg_b0rMDg6URdSE@ep-young-base-a60zcfd5-pooler.us-west-2.aws.neon.tech/neondb?sslmode=require
      - DO_SPACES_KEY=DO006QLQQA7UNWBNC8EC
      - DO_SPACES_SECRET=lR4M45YBulXQNaJf7chlDrnblbT0PXpW0HjLIeKxuGk
      - DO_SPACES_BUCKET_NAME=wtt-image-storage
      - DO_SPACES_ENDPOINT_URL=https://wtt-image-storage.sfo3.digitaloceanspaces.com

  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    depends_on:
      - backend
    volumes:
      - ./mobile:/app
      - /app/node_modules
    environment:
      - EXPO_PUBLIC_API_URL=http://localhost:8000